name: changelog_updates
on:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    #name: Verify Changelog file updated
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
#        with:
#          fetch-depth: 2

#      - name: Verify Changed Changelog
#        uses: nice-cxone/github-actions-shared/git/changed-files@master
#        id: verify-changed-files
#        with:
#          file-path: "*.md"

      - name: Verify Changed Changelog
        uses: jitterbit/get-changed-files@v1
        id: verify-changed-files

      - name: Run step only when files doesnt change.
        if: steps.verify-changed-files.outputs.files_changed != null
        run: |
          echo "One or more files in the docs folder has changed."
          echo "${{ github.event.head_commit.message }}"
          echo "steps.changed-files-specific.outputs: ${{ steps.changed-files-specific.outputs }}"
          echo "List all the files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"
