name: changelog_updates
on:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if CHANGELOG.md file was changed
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            CHANGELOG1.md

      - name: Run step if CHANGELOG.md file wasnt changed
        if: steps.changed-files-specific.outputs.any_changed == 'false'
        run: |
          echo "CHANGELOG.md file wasnt changed."
          exit 1
