name: changelog_updates
on:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            CHANGELOG1.md

      - name: Run step if MD file was changed
        if: steps.changed-files-specific.outputs.any_changed == 'false'
        run: |
          echo "CHANGELOF file wasnt changed."
          echo "List all the files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"
          exit 1
