name: changelog_updates
on:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    #name: Verify Changelog file updated
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{github.event.after}}

#      - name: Verify Changed Changelog
#        uses: nice-cxone/github-actions-shared/git/changed-files@master
#        id: verify-changed-files
#        with:
#          file-path: "*.md"

      - name: Verify Changed Changelog
        uses: jitterbit/get-changed-files@v1
        id: files
        with:
          format: 'csv'
      - run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for added_modified_file in "${added_modified_files[@]}"; do
            echo "Do something with this ${added_modified_file}."
          done
