name: changelog_updates
on:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    #name: Verify Changelog file updated
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

#      - name: Verify Changed Changelog
#        uses: nice-cxone/github-actions-shared/git/changed-files@master
#        id: verify-changed-files
#        with:
#          file-path: "*.md"

      - name: Verify Changed Changelog
        uses: tj-actions/verify-changed-files@v12
        id: verify-changed-files
        with:
          files: |
            *.md
            *.js

      - name: Run step only when files doesnt change.
        if: steps.verify-changed-files.outputs.files_changed != null
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
